FROM golang:1.12.9-alpine3.10 AS builder

ENV GO111MODULE=on
WORKDIR /go/src/server/
RUN apk add --no-cache gcc musl-dev ca-certificates git

COPY . ./

RUN CGO_ENABLED=0 go build -o /http-echo main.go

FROM scratch AS final
COPY --from=builder /http-echo /http-echo

ENTRYPOINT ["/http-echo"]
