version: '3.4'

services:

  go: &base
    build:
      context: .
      target: base
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SERVER_ECHO="It works as I expected"
    entrypoint:
      - /http-echo

  sh:
    <<: *base
    working_dir: /go/src/server/
    volumes:
      - .:/go/src/server/
    build:
      context: .
    entrypoint:
      - sh
