version: '3.4'

services:

  go: &base
    build:
      context: .
      target: base
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SERVER_ECHO="It works as I expected"
    entrypoint:
      - /http-echo

  sh:
    <<: *base
    working_dir: /go/src/server/
    volumes:
      - .:/go/src/server/
    entrypoint:
      - sh

  trivy:
    image: aquasec/trivy:0.10.2
    working_dir: /go/src/server/
    volumes:
      - ".:/go/src/server/"
      - "./cache:/root/.cache/"
      - "/var/run/docker.sock:/var/run/docker.sock"
