version: 2.1
jobs:
  e2e:
    machine: true
    steps:
      - checkout
      - run:
          name: E2E Test
          command: |
            make go
            make e2e

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy to Docker Hub
          command: |
            ./binbuild.sh ${CIRCLE_TAG}

workflows:
  version: 2
  untagged-build:
    jobs:
      - e2e
  tagged-build:
    jobs:
      - deploy:
          requires:
            - e2e
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
