version: 2.1
jobs:
  ut:
    machine: true
    steps:
      - checkout
      - run:
          name: Unit Test
          command: |
            echo "Unit Test"

  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Deploy to Docker Hub
          command: |
            echo ${CIRCLE_TAG}

workflows:
  version: 2
  untagged-build:
    jobs:
      - ut
  tagged-build:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
