version: 2.1
jobs:
  e2e:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: E2E Test
          command: |
            make go
            make e2e

  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Deploy to Docker Hub
          command: |
            echo ${DOCKER_PASSWORD} | base64 --decode | docker login -u $DOCKER_USER --password-stdin
            ./bin/build.sh ${CIRCLE_TAG}

workflows:
  version: 2
  untagged-build:
    jobs:
      - e2e
  tagged-build:
    jobs:
      - deploy:
          context: Docker
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
